pokemonpals/pokemon-online-store

package.json

changed name in package.json

---

package-lock.json
server/db/models/Inventory.js
server/db/models/Order.js
server/db/models/Pokemon.js
server/db/models/SubOrder.js
server/db/models/index.js

Created the Pokmeon, Inventory, SubOrder and Order Models

---

client/store/pokemonReducer.js
package-lock.json
server/api/index.js
server/api/pokemons.js

created pokemons.js in server>api for pokemon routes:
-all pokemons
-single pokemon 
(fyi: because pokemons are what we sell, the route is /products for all pokemons and /products/:pokemonId for single pokemon; if you guys think this is inhumane, I could change it)
I also modified the index.js under api, because I have to set up the router. 
This is incomplete because I need to verify the name of the pokemon model (waiting for Daniel's database)

Pokemon backend routers

---

client/store/pokemonReducer.js
package-lock.json

I created a new pokemonReducer.js under client>store
This is for the all pokemons view and the single pokemon view
Did not test, still waiting for the models from Daniel
Also: the initial state is empty, I'm thinking of using combinedReducer (because there is already a user reducer; so that we keep different reducers organized and clean)
I'm pushing this file now, just in case Vivian needs to use it for her features, so that she doesn't have to create any duplicates.

created pokemonReducer

---

script/seed.js
server/db/models/Pokemon.js
server/db/models/index.js

Updated associations and seeded the Pokemon table.

Corrected associations. Seeded Pokemon

---

client/components/PokemonCard.js
client/components/productList.js
client/store/index.js
client/store/loadingReducer.js
client/store/pokemonReducer.js
client/store/userReducer.js
server/api/pokemons.js

Product list

---

script/seed.js
server/db/models/index.js

Added a row in the Inventory table for future testing.

Seeded the Inventory table with 1 row with a quantity of 100 for testing

---

client/components/Login.js
client/components/myAccount.js
client/components/myAccount.specs.js
client/components/navbar.js
client/routes.js
client/store/index.js
client/store/userReducer.js

made error fixes to userReducer, removed OR user from line 26

---

client/components/SinglePokemon.js
client/routes.js
server/api/pokemons.js

still need to fix the refresh issue.

this is the single pokemon view

---

client/components/Login.js
client/routes.js
package-lock.json
script/seed.js
server/auth/index.js

User reducer: added log in page (must use db seed.js password when testing login)

---

client/components/auth-form.js

able to see the sign up form now

change Sign in -> Sign In

---

client/components/auth-form.js
client/components/index.js

Changed case from './SignUp' to './signup' in components/index

Sign up bug

---

client/components/signup.js

TRAVIS ISSUE:
SignUpform: in import UserForm line changed case './UserForm' to './userForm'

fix(components/signup): change case from UserForm to userForm

---

client/components/UpdateUserProfile.js
client/components/auth-form.js
client/components/navbar.js
client/components/user-home.js
client/store/userReducer.js
server/api/users.js

add user profile, still in progress

User profile

---

client/components/adminHome.js
client/components/adminPokemonView.js
client/components/adminSearchForm.js
client/components/index.js
client/components/productList.js
client/routes.js
client/store/pokemonReducer.js
server/api/pokemons.js
server/api/users.js

I added the adminHome, adminSearchForm and adminPokemonView files. Currently the only feature implemented is adding a pokemon to the database. My focus will be switched to protecting our routes so I wanted to make sure the code up until now successfully merges into master before proceeding.

Admin views

---

client/components/ProfileUpBySection.js
client/components/UpdateAddressForm.js
client/components/UpdateEmailForm.js
client/components/UpdateNameForm.js
client/components/UpdatePasswordForm.js
client/components/UpdateUserProfile.js
client/components/UserProfilePage.js

-implement the expansion feature
-make a correction to the spelling errors

User profile cosmetics

---

client/components/UserCart.js
client/routes.js

Add to cart

---

client/store/cartReducer.js

fix: remove button re-renders without refresh

---

client/components/SinglePokemon.js
client/components/UserCart.js
client/components/index.js
client/components/pokemonRender.js
client/store/cartReducer.js
server/api/cart.js

Add to cart - input quantity updates persist in database

---

client/components/adminAddProductForm.js
script/seed.js

Handling merge conflicts. Adding in admin files, slight Pokemon model change and console log to seed.

Checkout review page

---

client/components/checkoutPayment.js
client/components/checkoutReview.js

Payment in profile

---

server/api/cart.js

fix: cart input update replace missing route element

---

client/components/adminPokemonView.js

fixed:adminPokemon render page clean up

---

package-lock.json
package-lock2.json
package.json
server/index.js

fix: change session back to not saveUnitialized
